service: auth

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  stackName: art-center-auth-${self:provider.stage}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack