service: auth

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  stackName: art-center-auth-${self:provider.stage}


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
