service: ui-cdn

provider:
  name: aws
  stage: ${opt:stage}
  stackName: art-center-user-interface-cdn-${self:provider.stage}

custom:
  hosting:
    bucketName: ${self:provider.stackName}-hosting-bucket
  cdn:
    idSecretName: ${self:provider.stackName}-cdn-id-secret-name
    originId: ${self:provider.stackName}-cdn-origin-id
    originAccessIdentity: ${self:provider.stackName}-cdn-oai
  domain:
    name: ${self:custom.domain.options.${self:provider.stage}, self:custom.domain.options.other}
    hostedZone: "groffcole.com."
    options:
      other: ${self:provider.stage}.dev.groffcole.com
      dev: art.dev.groffcole.com
      prod: art.groffcole.com

resources:
  Resources:
    HostingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.hosting.bucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: true
          RestrictPublicBuckets: true

    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: ${self:custom.cdn.originAccessIdentity}